version: '3.8'
services:
  # User Service
  user-service:
    build:
      context: ./user-service  
    ports:
      - "8081:8080"  
    depends_on:
      - kafka

  # Journal Service
  journal-service:
    build:
      context: ./journal-service  
    ports:
      - "8082:8080"  
    depends_on:
      - kafka

  # Zookeeper for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  # Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"